spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


auth.secret=${AUTH_SECRET}

onesignal.app-id=${ONESIGNAL_APP_ID:cd2d3759-3204-4776-a116-2c8fc9900d14}
onesignal.rest-api-key=${ONESIGNAL_REST_API_KEY:}
app.web-url=${APP_WEB_URL:http://localhost:5173}

management.endpoint.health.show-details=always
